# Generated by Django 4.2.7 on 2023-11-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="finish_data",
            field=models.DateField(null=True, verbose_name="Дата окончания"),
        ),
    ]
