# Generated by Django 4.2.7 on 2023-12-05 17:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("project_app", "0002_task_finish_data"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="favoritetask",
            managers=[
                ("fav_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="task",
            managers=[
                ("user_obj", django.db.models.manager.Manager()),
            ],
        ),
    ]
